### ISSUE TITLE
Suggestion: why not using Arcsecond.io?

### ISSUE THREAD

**Issue by onekiloparsec** [juandesant/chilean_observatories.json#1]
Hello Juan,

I just stumbled upon this very fresh repo. A question though: why not putting this in Arcsecond.io, where we maintain an active encyclopaedia of observatories (and telescopes, and in the future instruments...) ?

https://www.arcsecond.io/observingsites

Once there, it can be used by many other people, and it is fetchable though Python module / cli (https://github.com/arcsecond-io/cli)

Best – Cédric (@arcsecond-io or @onekiloparsec)

**Comment by juandesant** [comment]
Hi, Cédric, I started doing this file because I needed it for a particular purpose, and I actually started looking at https://www.arcsecond.io/observingsites, but I found more sites. I also want to be able to add the operation start and (for some cases) operation end dates of them, which perhaps is not so useful for arcsecond.io.

Perhaps we can discuss this through email or Skype?

Cheers,
Juande. @juandesant

**Comment by onekiloparsec** [comment]
Sorry, I should have been more precise. The URL I gave you is the front ent. As for the data themselves, here there are, for Chile only:

https://api.arcsecond.io/observingsites/?country=Chile

As for the operations start and end, yes, it is interesting to me. Our goal is to make a kind of encyclopedia for these places, hence any type of information is useful.

Of course, we can continue by email, but I haven't found yours. Mine: cedric@arcsecond.io
